apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-qhtk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-qhtk
    app.kubernetes.io/part-of: cin4s-839-0027-app
  name: devfile-sample-qhtk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-qhtk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-qhtk
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0027-tenant/cin4s-839-0027-app/devfile-sample-qhtk@sha256:4553ad9e008e5bbdfd87b2f95db1ccc5c9cb6e312c83b40af2cc7960b1fcdabe
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
